import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./HeaderButton"
import HeaderButton from "./HeaderButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SSIS-Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log(`Someone logged in at ${new Date()}`)
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <div className="my-header">
            <HeaderButton text={"About"} myLink={"/about"} />
            <HeaderButton text={"Tables"} myLink={"/table"}/>
            <HeaderButton text={"Home"} myLink={"/"}/>
          </div>
        </header>
        <main className="my-main">
          {children}
        </main>
      </body>
    </html>
  );
}
